Switched Java worker to non-blocking
camunda-cloud/camunda-cloud-get-started pull request #16
Opened 2021-07-14 07:10 UTC by berndruecker

As discussed with Amara we see this as a quick win to non have too much blocking code right at the beginning

2021-07-14 18:42 UTC, akeller commented
Any side effects we need to document here by not doing a `join()`, or no?

2021-07-14 20:06 UTC, menski commented
If you don't join or check the result of the future at a later state you are not able to determine if your complete command was accepted by the broker, i.e. maybe you want to retry in this error case or discard the external outcome of the worker.

I don't see this as a blocker for this example code. But maybe not a good best practice for real applications, as they should do some kind of error handling. 

I don't know what you internally discussed so you came to the conclusion to remove it here.

2021-07-14 20:35 UTC, akeller commented
Let me fill you in 😄 

There is a concern that the subset of the Zeebe community (so pre-Cloud GA) using Java does not understand async vs. sync or non-blocking vs. blocking. They copy the examples as a starting point and use them in production. This is problematic for exactly what you mentioned above - "it may not be a good best practice for real applications". 

@berndruecker considered this a quick win without having to provide a ton of education around non-blocking vs. blocking. 

While I don't think we should have to teach people best practices for Java programming, I do think we need to offer some sort of protection for folks who will use the examples in production without understanding the consequences.

2021-07-15 02:26 UTC, jwulf commented
See this Forum thread: https://forum.camunda.io/t/how-to-know-that-an-exception-has-occurred-when-use-zeebeclient-in-this-way/2348

2021-07-15 06:12 UTC, berndruecker commented
@jwulf Unfortunately, the forum says this thread does not exist?
 
@akeller I was thinking a bit more about this - and especially about "protection for people that copy examples into prod without fully understanding them". Which I like. Having this in mind I changed my mind and think we should add an 

`.exceptionally(throwable -> {throw new RuntimeException("Could not complete job: " + throwable.getMessage(), throwable);})`

in the code - then I consider that production safe enough.  While I still think that line might be confusing for some folks - it is clearly the best compromise if we expect that this code makes it to production more often than we think (scales but also handles the exception, further there is less risk of simply forgetting the "join").

So I think we can live with the fact that the code is slightly more complicated and could also add a short hint that you can also simply "join()" if you want to run it blocking with a link to best practices.

And then we observe in real life. WDYT?
Happy to adjust the PR

2021-07-15 08:20 UTC, menski commented
I like your new proposal @berndruecker, and think it's a good compromise between async and still doing some error handling. My only comment is that as far as I know throwing an exception inside the `exceptionally` handler doesn't really raise the exception, it just breaks the future chaining but it's not transparent to the user. Maybe something like this would be okay?
```
 send().exceptionally(throwable -> {
            LOG.error("Failed to complete job", throwable);
            return null;
          });
```

2021-07-15 08:40 UTC, berndruecker commented
Good point - the more important fact is how to write code after the future completes successfully.

I am wondering if the "log exception" approach is beneficial in real life (compared to not handling the exception at all) - as I think unhandled exceptions will be logged on error level by default (if I am not mistaken)?

2021-07-15 09:15 UTC, menski commented
> the more important fact is how to write code after the future completes successfully.

Then maybe `whenComplete((result, error) -> {...})` would fit better?

> as I think unhandled exceptions will be logged on error level by default (if I am not mistaken)?

I'm no aware that this is how it works. As far as I know, as long as you are not requesting the result or attach a handler the future result is totally ignored.

2021-07-15 09:33 UTC, berndruecker commented
I am also not completely sure. I just know that in my typically Spring Boot applications this exception is logged - but that might totally depend on loggers and configs (which opens up another rabbit whole we don't want to open).

I like the proposal of using "whenComplete" to show that this is there - any objections?

2021-07-15 09:43 UTC, berndruecker commented
Added another commit as a proposal - WDYT?

If we keep that I would quickly also adjust the README

2021-07-15 09:48 UTC, menski commented
lgtm :+1:

2021-07-15 11:47 UTC, menski commented
BTW the spring worker also blocks right now, maybe we want to align it
https://github.com/camunda-cloud/camunda-cloud-get-started/blob/d315e0f0e469186b24c4985c0ff618f4da618f60/spring/src/main/java/io/camunda/getstarted/EmailWorker.java#L23

2021-07-15 12:37 UTC, berndruecker commented
Totally right! I aligned it and also adjusted the readme and added a small hint

2021-07-19 13:13 UTC, falko commented
+1

2021-07-19 14:57 UTC, akeller requested changes
Small typos

2021-07-19 14:57 UTC, akeller commented on java/README.md
> +This is discussed in more detial [this blog post about writing good workers for Camunda Cloud](https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862).
```suggestion
This is discussed in more detail in [this blog post about writing good workers for Camunda Cloud](https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862).
```

2021-07-19 14:57 UTC, akeller commented on java/README.md
> +This registers a callback to be executed if the command on the workflow engines was executed or resulted in an exception. This allows for parallelism, which is especially interesting in workers.
```suggestion
This registers a callback to be executed if the command on the workflow engine was executed or resulted in an exception. This allows for parallelism, which is especially interesting in workers. 
```

2021-07-19 14:57 UTC, akeller commented on spring/README.md
> +This registers a callback to be executed if the command on the workflow engines was executed or resulted in an exception. This allows for parallelism, which is especially interesting in workers.
```suggestion
This registers a callback to be executed if the command on the workflow engine was executed or resulted in an exception. This allows for parallelism, which is especially interesting in workers. 
```

2021-07-19 14:57 UTC, akeller commented on spring/README.md
> +This is discussed in more detial [this blog post about writing good workers for Camunda Cloud](https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862).
```suggestion
This is discussed in more detail in [this blog post about writing good workers for Camunda Cloud](https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862).
```

2021-07-20 06:57 UTC, berndruecker commented
Great - thanks! Applied the fixes

2021-07-21 10:28 UTC, berndruecker commented
@akeller Jut double-checking - anything left to do for me?

2021-07-21 13:20 UTC, akeller approved these changes

2021-07-21 13:21 UTC, merged

2021-07-21 13:21 UTC, akeller commented
Should be good! I'll squash and merge, but @menski will likely need to do a release :)